name: Trigger auto deployment for users

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/users-AutoDeployTrigger-8cb18165-910a-47df-8244-5b874b97bdf1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.USERS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.USERS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.USERS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: users/Dockerfile
          _targetLabelKey_: _targetLabel_
          registryUrl: gallensaintaigo-bqavbdfyg6gucyh6.azurecr.io
          registryUsername: ${{ secrets.USERS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERS_REGISTRY_PASSWORD }}
          containerAppName: users
          resourceGroup: MyGalendewagen
          imageToBuild: gallensaintaigo-bqavbdfyg6gucyh6.azurecr.io/users:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


